<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Draft' => '',
    'Expired At' => '过期时间',
    'Group ID' => '群组ID',
    'ID' => '',
    'Illegal parameters.' => '',
    'Introduce' => '描述',
    'Logo' => 'Logo',
    'Name' => '名称',
    'Payment ID' => '支付号',
    'Please do not join again.' => '',
    'Published' => '',
    'Rejected' => '',
    'Review' => '',
    'Role' => '角色',
    'Sign up success.' => '',
    'Update Group: {nameAttribute}' => '',
    'User ID' => '',
    'Allow Publish' => '允许发布',
    'Applicants' => '加入人数',
    'Are you sure you want to delete this item?' => '你确定要删除该项目？',
    'Blocked At' => '封锁时间',
    'Create Group' => '创建群组',
    'Created At' => '创建时间',
    'Delete' => '删除',
    'Fee' => '手续费',
    'Groups' => '群组',
    'Price' => '价格',
    'Reset' => '重置',
    'Save' => '保存',
    'Search' => '搜索',
    'Status' => '状态',
    'Update' => '更新',
    'Updated At' => '更新时间',
];
